ALTER TABLE "contact" DROP CONSTRAINT "contact_principal_id_principal_id_fkey", ADD CONSTRAINT "contact_principal_id_principal_id_fkey" FOREIGN KEY ("principal_id") REFERENCES "principal"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "document" DROP CONSTRAINT "document_principal_id_principal_id_fkey", ADD CONSTRAINT "document_principal_id_principal_id_fkey" FOREIGN KEY ("principal_id") REFERENCES "principal"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "hire" DROP CONSTRAINT "hire_caller_id_principal_id_fkey", ADD CONSTRAINT "hire_caller_id_principal_id_fkey" FOREIGN KEY ("caller_id") REFERENCES "principal"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "hire" DROP CONSTRAINT "hire_listing_id_listing_id_fkey", ADD CONSTRAINT "hire_listing_id_listing_id_fkey" FOREIGN KEY ("listing_id") REFERENCES "listing"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "listing" DROP CONSTRAINT "listing_principal_id_principal_id_fkey", ADD CONSTRAINT "listing_principal_id_principal_id_fkey" FOREIGN KEY ("principal_id") REFERENCES "principal"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "log" DROP CONSTRAINT "log_principal_id_principal_id_fkey", ADD CONSTRAINT "log_principal_id_principal_id_fkey" FOREIGN KEY ("principal_id") REFERENCES "principal"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "message" DROP CONSTRAINT "message_thread_id_thread_id_fkey", ADD CONSTRAINT "message_thread_id_thread_id_fkey" FOREIGN KEY ("thread_id") REFERENCES "thread"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "payout" DROP CONSTRAINT "payout_account_id_account_id_fkey", ADD CONSTRAINT "payout_account_id_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "principal" DROP CONSTRAINT "principal_account_id_account_id_fkey", ADD CONSTRAINT "principal_account_id_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "thread" DROP CONSTRAINT "thread_principal_id_principal_id_fkey", ADD CONSTRAINT "thread_principal_id_principal_id_fkey" FOREIGN KEY ("principal_id") REFERENCES "principal"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "usage" DROP CONSTRAINT "usage_account_id_account_id_fkey", ADD CONSTRAINT "usage_account_id_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "usage" DROP CONSTRAINT "usage_hire_id_hire_id_fkey", ADD CONSTRAINT "usage_hire_id_hire_id_fkey" FOREIGN KEY ("hire_id") REFERENCES "hire"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "worker" DROP CONSTRAINT "worker_account_id_account_id_fkey", ADD CONSTRAINT "worker_account_id_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE;